name: "AI-BOM Scan"
description: "Discover and inventory AI/LLM components in your codebase"
author: "Trusera"

# Required permissions in calling workflow:
#   permissions:
#     security-events: write   # For SARIF upload to GitHub Code Scanning
#     contents: read           # For checkout

branding:
  icon: "shield"
  color: "blue"

inputs:
  path:
    description: "Path to scan"
    required: false
    default: "."
  format:
    description: "Output format (sarif, json, cyclonedx, table, markdown)"
    required: false
    default: "sarif"
  severity:
    description: "Minimum severity to report (critical, high, medium, low)"
    required: false
    default: ""
  output:
    description: "Output file path"
    required: false
    default: "ai-bom-results.sarif"
  upload-sarif:
    description: "Upload SARIF results to GitHub Code Scanning"
    required: false
    default: "true"
  fail-on:
    description: "Fail if any component meets or exceeds severity (critical, high, medium, low)"
    required: false
    default: ""
  policy-file:
    description: "Path to YAML policy file for enforcement"
    required: false
    default: ""
  python-version:
    description: "Python version to use"
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install ai-bom
      shell: bash
      run: pip install ai-bom

    - name: Run ai-bom scan
      shell: bash
      continue-on-error: true  # Scan findings should not fail the workflow
      run: |
        ARGS="scan ${{ inputs.path }} --format ${{ inputs.format }} -o ${{ inputs.output }} --quiet"
        if [ -n "${{ inputs.severity }}" ]; then
          ARGS="$ARGS --severity ${{ inputs.severity }}"
        fi
        if [ -n "${{ inputs.fail-on }}" ]; then
          ARGS="$ARGS --fail-on ${{ inputs.fail-on }}"
        fi
        if [ -n "${{ inputs.policy-file }}" ]; then
          ARGS="$ARGS --policy ${{ inputs.policy-file }}"
        fi
        ai-bom $ARGS

    - name: Upload SARIF to GitHub Code Scanning
      if: ${{ inputs.upload-sarif == 'true' && inputs.format == 'sarif' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.output }}
