name: "AI-BOM Scan"
description: "Discover and inventory AI/LLM agents, models, and API integrations in your codebase. Generates SBOM-style reports in CycloneDX, SARIF, SPDX, and more."
author: "Trusera"

# Required permissions in calling workflow:
#   permissions:
#     security-events: write   # For SARIF upload to GitHub Code Scanning
#     contents: read           # For checkout

branding:
  icon: "shield"
  color: "blue"

inputs:
  path:
    description: "Directory to scan"
    required: false
    default: "."
  format:
    description: "Output format (cyclonedx, sarif, spdx, table, html, markdown, csv)"
    required: false
    default: "table"
  output:
    description: "Output file path (optional — prints to stdout if not set)"
    required: false
    default: ""
  fail-on:
    description: "Fail the pipeline if any component meets or exceeds this severity (critical, high, medium, low)"
    required: false
    default: ""
  scan-level:
    description: "Scanning depth: quick (pattern-matching only), standard (all scanners), deep (standard + AST analysis)"
    required: false
    default: "standard"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install ai-bom
      shell: bash
      run: pip install ai-bom

    - name: Run ai-bom scan
      id: scan
      shell: bash
      run: |
        # Build the base command
        ARGS="scan ${{ inputs.path }} --format ${{ inputs.format }} --quiet"

        # Output file
        if [ -n "${{ inputs.output }}" ]; then
          ARGS="$ARGS -o ${{ inputs.output }}"
        elif [ "${{ inputs.format }}" = "sarif" ]; then
          # Default SARIF output path for upload step
          ARGS="$ARGS -o ai-bom-results.sarif"
          echo "sarif_file=ai-bom-results.sarif" >> "$GITHUB_OUTPUT"
        fi

        # Scan level
        if [ "${{ inputs.scan-level }}" = "deep" ]; then
          ARGS="$ARGS --deep"
        fi

        # Fail-on severity threshold
        if [ -n "${{ inputs.fail-on }}" ]; then
          ARGS="$ARGS --fail-on ${{ inputs.fail-on }}"
        fi

        echo "Running: ai-bom $ARGS"
        ai-bom $ARGS

    - name: Upload SARIF to GitHub Code Scanning
      if: ${{ inputs.format == 'sarif' && (steps.scan.outputs.sarif_file != '' || inputs.output != '') }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif_file || inputs.output }}
